/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DatVe;
import 
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ADMIN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_gioitinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_stt = new javax.swing.JTextField();
        tf_hovaten = new javax.swing.JTextField();
        cbx_nam = new javax.swing.JCheckBox();
        cbx_nu = new javax.swing.JCheckBox();
        cbbx_dotuoi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_diachi = new javax.swing.JTextArea();
        tf_sdt = new javax.swing.JTextField();
        cbbx_tuyenduong = new javax.swing.JComboBox<>();
        cbbx_giokhoihanh = new javax.swing.JComboBox<>();
        btn_datve = new javax.swing.JButton();
        btn_huybo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("STT");

        jLabel2.setText("Họ và tên");

        jLabel3.setText("Giới tính");

        jLabel4.setText("Độ tuổi");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Điện thoại");

        jLabel7.setText("Tuyến đường");

        jLabel8.setText("Giờ khởi hành");

        btng_gioitinh.add(cbx_nam);
        cbx_nam.setText("Nam");

        btng_gioitinh.add(cbx_nu);
        cbx_nu.setText("Nu");

        cbbx_dotuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 20", "20-30", "30-40", "trên 40" }));

        ta_diachi.setColumns(20);
        ta_diachi.setRows(5);
        jScrollPane1.setViewportView(ta_diachi);

        cbbx_tuyenduong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cần Thơ – Châu Đốc", "Cần Thơ – Sài Gòn" }));

        cbbx_giokhoihanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3:45", "6:30" }));

        btn_datve.setText("Đặt vé");
        btn_datve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datveActionPerformed(evt);
            }
        });

        btn_huybo.setText("Hủy bỏ");
        btn_huybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_hovaten)
                        .addComponent(tf_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbx_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbx_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(tf_sdt)
                        .addComponent(cbbx_dotuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbx_tuyenduong, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbx_giokhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_datve)))
                        .addGap(10, 10, 10)
                        .addComponent(btn_huybo)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_stt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(tf_hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_nam)
                    .addComponent(cbx_nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbx_dotuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbx_tuyenduong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbbx_giokhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_datve)
                    .addComponent(btn_huybo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_datveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datveActionPerformed
        // TODO add your handling code here:
        String stt = tf_stt.getText();
        String ten = tf_hovaten.getText();
       String gioitinh = getgioitinh(btng_gioitinh);
//        JRadioButton gett = (JRadioButton) btng_gioitinh.getSelection();
//        String gioitinh = gett.getText();
        String dotuoi = (String) cbbx_dotuoi.getSelectedItem();
        String diachi = ta_diachi.getText();
        String sdt = tf_sdt.getText();
        String tuyen = (String) cbbx_tuyenduong.getSelectedItem();
        String gio = (String) cbbx_giokhoihanh.getSelectedItem();

        if (!stt.matches("\\d+")) {
            System.err.println("STT phai la mot chu so");
        } else if (ten.isBlank()) {
            System.err.println("Khong duoc bo trong ten");
        } else if (diachi.isBlank()) {
            System.err.println("Khong duoc de trong dia chi");
        } else if (sdt.isBlank()) {
            System.err.println("Khong duoc de trong so dien thoai");
        } else {
            System.out.println("STT:" + stt);
            System.out.println("Ho va ten: " + ten);
            System.out.println("Gioi Tinh: " + gioitinh);
            System.out.println("Do tuoi: " + dotuoi);
            System.out.println("Dia chi: " + diachi);
            System.out.println("So dien thoai: " + sdt);
            System.out.println("Tuyen: " + tuyen);
            System.out.println("Gio khoi hanh: " + gio);
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl = "jdbc:sqlserver://LAPTOP-C2JCA4PK\\SQLEXPRESS:1433;trustServerCertificate=true;databaseName=VE_XE;user=sa;password=sa2019";
                Connection con = DriverManager.getConnection(dbUrl);
                String sql = "INSERT INTO ve_xe(stt" +
"      ,ho_ten" +
"      ,gioi_tinh" +
"      ,do_tuoi" +
"      ,dia_chi" +
"      ,dien_thoai" +
"      ,tuyen_duong" +
"      ,gio_khoi_hanh) VALUES(?,?,?,?,?,?,?,?)";
                PreparedStatement p = con.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(stt));
                p.setString(2, ten);
                p.setString(3, gioitinh);
                p.setString(4, dotuoi);
                p.setString(5, diachi);
                p.setString(6, sdt);
                p.setString(7, tuyen);
                p.setString(8, gio);
                p.executeUpdate();
                System.out.println("-------------\nDat ve thanh cong\n-------");
                con.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btn_datveActionPerformed

    private void btn_huyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyboActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_huyboActionPerformed
    private String getgioitinh(ButtonGroup btn) {
        Enumeration<AbstractButton> allgioitinh = btn.getElements();
        while (allgioitinh.hasMoreElements()) {
            AbstractButton button = allgioitinh.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datve;
    private javax.swing.JButton btn_huybo;
    private javax.swing.ButtonGroup btng_gioitinh;
    private javax.swing.JComboBox<String> cbbx_dotuoi;
    private javax.swing.JComboBox<String> cbbx_giokhoihanh;
    private javax.swing.JComboBox<String> cbbx_tuyenduong;
    private javax.swing.JCheckBox cbx_nam;
    private javax.swing.JCheckBox cbx_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_diachi;
    private javax.swing.JTextField tf_hovaten;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_stt;
    // End of variables declaration//GEN-END:variables
}
