/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DETHI;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
/**
 *
 * @author ADMIN
 */
public class DETHI extends javax.swing.JFrame {

    /**
     * Creates new form DETHI
     */
    public DETHI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnthemmoi = new javax.swing.JButton();
        txtmahanghoa = new javax.swing.JTextField();
        txttenhang = new javax.swing.JTextField();
        cboloaihang = new javax.swing.JComboBox<>();
        txtnhasanxuat = new javax.swing.JTextField();
        cbodonvitinh = new javax.swing.JComboBox<>();
        txtdongia = new javax.swing.JTextField();
        txtngaynhaphang = new javax.swing.JTextField();
        btnhuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã hàng hóa");

        jLabel2.setText("Tên hàng");

        jLabel3.setText("Loại hàng");

        jLabel4.setText("Nhà sản xuất");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Đơn giấ");

        jLabel7.setText("Ngày nhập hàng");

        btnthemmoi.setText("Thêm mới");
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        cboloaihang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện thoại", "Máy tính", "Tivi" }));

        cbodonvitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cái", "chiếc" }));

        btnhuy.setText("Hủy");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenhang)
                            .addComponent(cboloaihang, 0, 202, Short.MAX_VALUE)
                            .addComponent(txtnhasanxuat)
                            .addComponent(cbodonvitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdongia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnthemmoi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhuy)
                            .addComponent(txtngaynhaphang))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboloaihang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnhasanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbodonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtngaynhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemmoi)
                    .addComponent(btnhuy))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        String ma = txtmahanghoa.getText();
        String tenhang = txttenhang.getText();
        String loaihang = (String) cboloaihang.getSelectedItem();
        String nsx = txtnhasanxuat.getText();
        String donvi = (String) cbodonvitinh.getSelectedItem();
        String dongia = txtdongia.getText();
        String ngay = txtngaynhaphang.getText();
        
        if (!ma.matches("H[a-zA-Z0-9]{5}")){
            System.err.println("Mã hàng hóa phải bắt đầu bằng chữ cái H và có 6 ký tự");
        }else if(tenhang.isBlank()){
            System.err.println("Tên hàng yêu cầu không rỗng");
        }else if(!nsx.equalsIgnoreCase("sharp") && !nsx.equalsIgnoreCase("samsung") && !nsx.equalsIgnoreCase("toshiba")){
            System.err.println("Nhà sản xuất phải chọn một trong các giá trị: Sharp, Samsung, Toshiba");
        }else if(!dongia.matches("\\d+")){
            System.err.println("Đơn giá bắt buộc là số lớn hơn 0");
        }else if(!isValidDate(ngay)){
            System.err.println("Ngày nhập hàng theo định dạng DD/MM/YYYY và từ ngày hiện tại về sau");
        }else{
            System.out.println("Ma hang hoa: "+ma);
            System.out.println("Ten hang hoa: "+tenhang);
            System.out.println("Loai hang: "+loaihang);
            System.out.println("Nha san xuat: "+nsx);
            System.out.println("Don vi tinh: "+donvi);
            System.out.println("Don gia: "+dongia);
            System.out.println("Ngay nhap hang: "+ngay);
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl = "jdbc:sqlserver://LAPTOP-C2JCA4PK\\SQLEXPRESS:1433;databaseName=hanghoa;user=sa;password=sa2019";
                Connection c = DriverManager.getConnection(dbUrl);
                String sql = "insert into hang_hoa1" +" values( ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, ma);
                p.setString(2, tenhang);
                p.setString(3, loaihang);
                p.setString(4, nsx);
                p.setString(5, donvi);
                p.setString(6, dongia);
                p.setString(7, ngay);
                p.executeUpdate();
                System.out.println("Thanh cong! Them hang hoa thanh cong");
                c.close();
                
            } catch (Exception e) {
                System.err.println("That bai! Ma hang da ton tai");
                
            }
            
        }
                
    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnhuyActionPerformed
public boolean isValidDate(String input){
    try {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        Date currentDay = new Date();
        String check = f.format(currentDay);
        Date ngaynhap = f.parse(input);
        String ngay = f.format(ngaynhap);
        if(check.equals(ngay) || ngaynhap.after(currentDay)){
            return true;
        }else
            return false;
    } catch (Exception e) {
        return false;
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DETHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DETHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DETHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DETHI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DETHI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JComboBox<String> cbodonvitinh;
    private javax.swing.JComboBox<String> cboloaihang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmahanghoa;
    private javax.swing.JTextField txtngaynhaphang;
    private javax.swing.JTextField txtnhasanxuat;
    private javax.swing.JTextField txttenhang;
    // End of variables declaration//GEN-END:variables
}
