/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DVD;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import java.sql.*;

/**
 *
 * @author ADMIN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setTitle("DVD Datalog");
        setLocationRelativeTo(null);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbUrl = "jdbc:sqlserver://LAPTOP-C2JCA4PK\\SQLEXPRESS:1433;databaseName=DVDLibrary;user=sa;password=sa2019";
            Connection con = DriverManager.getConnection(dbUrl);
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select * from DVD");
            while (r.next()){
                System.out.println("DVDCodeNo: "+r.getInt(1)+" DVD Title: "+r.getString("DVDTitle"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSubTitles = new javax.swing.ButtonGroup();
        lblHeading = new javax.swing.JLabel();
        lblDVDCodeNo = new javax.swing.JLabel();
        lbllDVDTitle = new javax.swing.JLabel();
        lblDVDLang = new javax.swing.JLabel();
        lblDVDPrice = new javax.swing.JLabel();
        lblDVDSubTitles = new javax.swing.JLabel();
        txtCodeNo = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        cboLang = new javax.swing.JComboBox<>();
        updPrice = new javax.swing.JSpinner();
        radYes = new javax.swing.JCheckBox();
        radNo = new javax.swing.JCheckBox();
        btnAddNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblDollars = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeading.setText("DVD Datalog");

        lblDVDCodeNo.setText("DVD Code Number");

        lbllDVDTitle.setText("DVD Title");

        lblDVDLang.setText("Langague");

        lblDVDPrice.setText("Price");

        lblDVDSubTitles.setText("SubTitles");

        txtCodeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeNoActionPerformed(evt);
            }
        });

        cboLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "French", "Chinese" }));

        updPrice.setMaximumSize(new java.awt.Dimension(150, 150));
        updPrice.setMinimumSize(new java.awt.Dimension(0, 0));
        updPrice.setValue(+5);

        grpSubTitles.add(radYes);
        radYes.setSelected(true);
        radYes.setText("Yes");

        grpSubTitles.add(radNo);
        radNo.setText("No");

        btnAddNew.setText("Add");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblDollars.setText("Dollars");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDVDCodeNo)
                            .addComponent(lbllDVDTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDVDLang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDVDPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDVDSubTitles, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddNew)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading)
                    .addComponent(txtCodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboLang, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDollars))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radYes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radNo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDVDCodeNo)
                    .addComponent(txtCodeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllDVDTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDVDLang)
                    .addComponent(cboLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDVDPrice)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDollars)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDVDSubTitles)
                    .addComponent(radYes)
                    .addComponent(radNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnSave)
                    .addComponent(btnExit))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeNoActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        
        try {
            xoaBang();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbUrl = "jdbc:sqlserver://LAPTOP-C2JCA4PK\\SQLEXPRESS:1433;databaseName=DVDLibrary;user=sa;password=sa2019";
            Connection con = DriverManager.getConnection(dbUrl);
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select max(DVDCodeNo) from DVD");
            r.next();
            int max = r.getInt(1);
            max++;
            txtCodeNo.setText("" + max);
            txtCodeNo.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
       xoaBang();
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String CodeNo = txtCodeNo.getText();
        String Title = txtTitle.getText();
        String Lang = (String) cboLang.getSelectedItem();
        Object price = updPrice.getValue();
        String Sub = getValueSubtitle(grpSubTitles);
        if(CodeNo.isBlank()){
            System.err.println("Khong duoc de trong Code Number");
        }else if(Title.isBlank()){
            System.err.println("Khong duoc de trong Title");
        }else if(price == null){
            System.err.println("Khong duoc de trong price");
        }else if(Sub == null ){
            System.err.println("Khong duoc de trong");
        }
        else{
            int Price = (int) price;
            System.out.println("DVD Code Number: "+CodeNo);
            System.out.println("DVD Title: "+Title);
            System.out.println("DVD Language: "+Lang);
            System.out.println("Price: "+Price);
            boolean t;
            if (Sub.equalsIgnoreCase("Yes")){
                t =true;
            }else{
                t = false;
            }
            System.out.println("SubTitle: "+t);
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl = "jdbc:sqlserver://LAPTOP-C2JCA4PK\\SQLEXPRESS:1433;trustServerCertificate=true;databaseName=DVDLibrary;user=sa;password=sa2019";
                Connection con = DriverManager.getConnection(dbUrl);
                String sql = "insert into DVD" + " values( ?, ?, ?, ?, ?)";
                PreparedStatement p = con.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(CodeNo));
                p.setString(2, Title);
                p.setString(3, Lang);
                p.setBoolean(4, t);
                p.setInt(5, Price);
                p.executeUpdate();
                System.out.println("-------------\nAdd thanh cong!!!!");
                con.close();
                xoaBang();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private void xoaBang(){
        txtCodeNo.setText("");
        txtTitle.setText("");
        cboLang.setSelectedIndex(0);
        updPrice.setValue(5);
        radYes.setSelected(true);
        radNo.setSelected(false);
    }
    
    private String getValueSubtitle(ButtonGroup grp){
        Enumeration<AbstractButton> all = grp.getElements();
        while (all.hasMoreElements()){
            AbstractButton t = all.nextElement();
            if(t.isSelected()){
                return t.getText();
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboLang;
    private javax.swing.ButtonGroup grpSubTitles;
    private javax.swing.JLabel lblDVDCodeNo;
    private javax.swing.JLabel lblDVDLang;
    private javax.swing.JLabel lblDVDPrice;
    private javax.swing.JLabel lblDVDSubTitles;
    private javax.swing.JLabel lblDollars;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lbllDVDTitle;
    private javax.swing.JCheckBox radNo;
    private javax.swing.JCheckBox radYes;
    private javax.swing.JTextField txtCodeNo;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JSpinner updPrice;
    // End of variables declaration//GEN-END:variables
}
