/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DangNhap;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */

public class NewFrameDangNhap extends javax.swing.JFrame {
   account tk = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456");
   account tk1 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456");
   account tk2 = new account("duyhungduong@gmail.com", "Duong", "Hung", "12345");
   account tk3 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456");
   account tk4 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456");
   account tk5 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   account tk6 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   account tk7 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   account tk8 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   account tk9 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   account tk10 = new account("duyhungduong@gmail.com", "Duong", "Hung", "123456@789abc");
   
    /**
     * Creates new form NewFrameDangNhap
     */
    public NewFrameDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        chuyenten = new javax.swing.JLabel();
        chuyenemail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        thongbao1 = new javax.swing.JLabel();
        thongbao2 = new javax.swing.JLabel();
        quenmk = new javax.swing.JLabel();
        tieptheo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nhapsai = new javax.swing.JLabel();

        matkhau = new javax.swing.JPasswordField();
        matkhau.setVisible(false);
        ngonngu = new javax.swing.JComboBox<>();
        help = new javax.swing.JLabel();
        quyen = new javax.swing.JLabel();
        typical = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        chuyenten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chuyenten.setForeground(new java.awt.Color(51, 51, 51));
        chuyenten.setText("Đăng Nhập");

        chuyenemail.setForeground(new java.awt.Color(102, 102, 102));
        chuyenemail.setText("Sử dụng tài khoản Google của bạn");

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setText("Email hoặc số điện thoại"); // NOI18N
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Bạn quên địa chỉ email?");

        thongbao1.setText("Đây không phải máy tính của bạn? Hãy sử dụng");

        thongbao2.setText("chế độ Khách để đăng nhập một cách riêng tư");

        quenmk.setForeground(new java.awt.Color(0, 51, 255));
        quenmk.setText("Tạo tài khoản");

        tieptheo.setBackground(new java.awt.Color(0, 51, 255));
        tieptheo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tieptheo.setForeground(new java.awt.Color(255, 255, 255));
        tieptheo.setText("Tiếp theo");
        tieptheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieptheoActionPerformed(evt);
            }
        });
        tieptheo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tieptheoKeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DangNhap/google2.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        nhapsai.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        nhapsai.setForeground(new java.awt.Color(255, 0, 51));
        nhapsai.setText("Không tìm thấy Tài khoản Google của bạn ");
        nhapsai.setVisible(false);
        nhapsai.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                nhapsaiComponentHidden(evt);
            }
        });

        matkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matkhauKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(thongbao1)
                    .addComponent(thongbao2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(quenmk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tieptheo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(nhapsai, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkhau))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(chuyenten)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(chuyenemail)
                        .addGap(64, 64, 64))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chuyenten, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chuyenemail)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(nhapsai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongbao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thongbao2)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quenmk)
                    .addComponent(tieptheo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        ngonngu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "English" }));

        help.setForeground(new java.awt.Color(51, 51, 51));
        help.setText("Trợ giíup");

        quyen.setForeground(new java.awt.Color(51, 51, 51));
        quyen.setText("Quyền riêng tư");

        typical.setForeground(new java.awt.Color(51, 51, 51));
        typical.setText("Điều khoản");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(help)
                        .addGap(18, 18, 18)
                        .addComponent(quyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typical))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngonngu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngonngu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(help)
                    .addComponent(quyen)
                    .addComponent(typical))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void tieptheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieptheoActionPerformed
        // TODO add your handling code here:
        String c = email.getText();
        if(c!=null){
            if(c.compareTo(tk.getEmail())==0){
               boolean b1,b2;
               b1 = thongbao1.isVisible();
               b2 = thongbao2.isVisible();
               thongbao1.setVisible(!b1);
               thongbao2.setVisible(!b2);
               
               email.setVisible(false);
               matkhau.setVisible(true);
               
               quenmk.setText("Bạn quên mật khẩu?");
                       
               // 
               chuyenten.setText(tk.getTen()+" "+tk.getHo());
               chuyenemail.setText(tk.getEmail());
               //email.setText("Nhập mật khẩu của bạn");
               
               char[] p = matkhau.getPassword();
               int i = 0;
               if(p!=null){
               i++;
               if(tk.getPassword().equals(new String(p))){
                       //System.out.println("Dang nhap thanh cong");
                       ngonngu.setVisible(false);
                       panel.setVisible(false);
                       help.setVisible(false);
                       quyen.setVisible(false);
                       typical.setVisible(false);
                       JFrame f1 = new JFrame("Thanh Cong");
                       JOptionPane.showMessageDialog(f1, "Chúc mừng bạn đăng nhập thành công!", "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                       System.exit(0);
               }else{
                       if(i>2){nhapsai.setText("Nhập mật khẩu sai");
                       boolean visible = nhapsai.isVisible();
                       nhapsai.setVisible(!visible);}
                       
               }
               }
//               }else{
//                   nhapsai.setText("Nhập mật khẩu sai");
//                   boolean visible = nhapsai.isVisible();
//                   nhapsai.setVisible(!visible);
//               }
               
            }else{
               
                nhapsai.setVisible(true);
            }
        }else{
          //  boolean visible = nhapsai.isVisible();
            nhapsai.setVisible(true);
        }
        
        
    }//GEN-LAST:event_tieptheoActionPerformed
    
    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        email.setText("");
    }//GEN-LAST:event_emailMouseClicked

    private void nhapsaiComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nhapsaiComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapsaiComponentHidden

    private void tieptheoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tieptheoKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
//            try {
//            String c = email.getText();
//        if(c!=null){
//            if(c.compareTo(tk.getEmail())==0){
//               boolean b1,b2;
//               b1 = thongbao1.isVisible();
//               b2 = thongbao2.isVisible();
//               thongbao1.setVisible(!b1);
//               thongbao2.setVisible(!b2);
//               
//               email.setVisible(false);
//               matkhau.setVisible(true);
//               
//               quenmk.setText("Bạn quên mật khẩu?");
//                       
//               // 
//               chuyenten.setText(tk.getTen()+" "+tk.getHo());
//               chuyenemail.setText(tk.getEmail());
//               //email.setText("Nhập mật khẩu của bạn");
//               
//               char[] p = matkhau.getPassword();
//               if(p!=null){
//               if(tk.getPassword().equals(new String(p))){
//                       //System.out.println("Dang nhap thanh cong");
//                       ngonngu.setVisible(false);
//                       panel.setVisible(false);
//                       help.setVisible(false);
//                       quyen.setVisible(false);
//                       typical.setVisible(false);
//                       JFrame f1 = new JFrame("Thanh Cong");
//                       JOptionPane.showMessageDialog(f1, "Chúc mừng bạn đăng nhập thành công!", "Thành Công", JOptionPane.INFORMATION_MESSAGE);
//                       
//               }else{
//                       nhapsai.setText("Nhập mật khẩu sai");
//                       boolean visible = nhapsai.isVisible();
//                       nhapsai.setVisible(!visible);
//               }
//               }
////               }else{
////                   nhapsai.setText("Nhập mật khẩu sai");
////                   boolean visible = nhapsai.isVisible();
////                   nhapsai.setVisible(!visible);
////               }
//               
//            }
//        }else{
//                boolean visible = nhapsai.isVisible();
//                nhapsai.setVisible(!visible);
//            }
//        } catch (HeadlessException e) {
//        }
//        }   
    }//GEN-LAST:event_tieptheoKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tieptheo.doClick();
        }
    }//GEN-LAST:event_emailKeyPressed

    private void matkhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matkhauKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tieptheo.doClick();
        }
    }//GEN-LAST:event_matkhauKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       // nhapsai.setVisible(false);
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NewFrameDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chuyenemail;
    private javax.swing.JLabel chuyenten;
    private javax.swing.JTextField email;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JComboBox<String> ngonngu;
    private javax.swing.JLabel nhapsai;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel quenmk;
    private javax.swing.JLabel quyen;
    private javax.swing.JLabel thongbao1;
    private javax.swing.JLabel thongbao2;
    private javax.swing.JButton tieptheo;
    private javax.swing.JLabel typical;
    // End of variables declaration//GEN-END:variables
}
